// scr_animation_constants
#macro ANIM_WALK_RIGHT_START 144
#macro ANIM_WALK_RIGHT_END 152
#macro ANIM_WALK_UP_START 105
#macro ANIM_WALK_UP_END 113
#macro ANIM_WALK_DOWN_START 131
#macro ANIM_WALK_DOWN_END 139
#macro ANIM_WALK_LEFT_START 118
#macro ANIM_WALK_LEFT_END 126